max-line-length: 120

inherits:
  - strictness_veryhigh

ignore-patterns:
  - ^setup.py$

bandit:
  run: false

dodgy:
  run: false

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: true

pep257:
  disable:
    - D400
    - D401

pycodestyle:
  options:
    disable:
      - E203 # https://github.com/PyCQA/pycodestyle/issues/373
      - E304
      - E265
      - E266
      - E501 # Covered by pylint
      - W291
      - W292
      - W391
      - N811
      - N812
      - N813
      - N814

pyflakes:
  run: true
  disable:
    - F401

pylint:
  run: false

pyroma:
  disable:
    - PYR15
    - PYR18
    - PYR17

vulture:
  run: true
