blank_issues_enabled: true
contact_links:
  - name: ❓ Questions
    url: https://github.com/cobbler/cobbler/discussions
    about: Ask questions here
  - name: 💬 Gitter Chat
    url: https://gitter.im/cobbler/community
    about: Chat with the Cobbler community
  - name: 📬 Development mailing list
    url: https://groups.google.com/forum/#!forum/cobbler-users
    about: The developer mailing list
