name: Coverage Upload

on:
  workflow_run:
    workflows: [Testing Cobbler]
    types:
      - completed

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/dawidd6/action-download-artifact
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: coverage-report
          workflow: testing.yml
          allow_forks: true
          workflow_conclusion: success
      # https://github.com/codacy/codacy-coverage-reporter-action
      # - name: Run codacy-coverage-reporter
      #   uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #     coverage-reports: coverage.xml
      - name: Publish Code Coverage Results
        run: |
          auth="--project-token ${{ secrets.CODACY_PROJECT_TOKEN }}"
          commit_uuid="--commit-uuid ${{ github.event.workflow_run.head_sha }}"

          bash <(curl -Ls https://coverage.codacy.com/get.sh) report $auth $commit_uuid -r coverage.xml --partial &&\
          bash <(curl -Ls https://coverage.codacy.com/get.sh) final $auth $commit_uuid
